services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
      
  redis:
    image: redis:alpine
    container_name: laravel_redis
    ports:
      - "6379:6379"
      
  queue:
    build: .
    container_name: laravel_queue
    command: supervisord -c /etc/supervisor/conf.d/supervisord.conf
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - redis
volumes:
  mysql_data: