[supervisord]
nodaemon=true

[program:apache]
command=apache2-foreground
autostart=true
autorestart=true
priority=10

[program:laravel-worker]
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3 --timeout=90 --max-time=3600
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderruser=www-data
priority=20